# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84579f1d11a091617fa3c6f33c73a409dd7aee8a375810672f4eae7f6b011b5d2b2f3406f4f6ad2d96fdcc7f9af266cd8e4906a8a9dd92071ec89ac2c44a56f6

test:
  secret_key_base: fc323c95c7aea23c6229f6b9f432210af1e15abe7f49f979f04d8090aca2560a0b6a7e11ff5c6b697d408296b37ab64ab58f207d4376d2195658e08263c3aa58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
